version: '3.1'

services:
  db:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: my_app
      POSTGRES_DB: my_app
    container_name: toolkit_db
    ports:
      - 54321:5432
    expose:
      - '54321'
    restart: 'no'
    volumes:
      - ./data:/var/lib/postgresql/data

  db-test:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: my_app
      POSTGRES_DB: my_app_test
    container_name: toolkit_db_test
    ports:
      - 54322:5432
    expose:
      - '54322'
    restart: 'no'

  app:
    privileged: true
    container_name: cake_test_app
    env_file:
      - .env
    build: .
    volumes:
      - .:/var/www/html
      - ${PWD}/mount.sh:/var/scripts/mount.sh
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
      - NET_ADMIN
    command: bash -c "chmod 755 /var/scripts/mount.sh && /var/scripts/mount.sh && apachectl -D FOREGROUND"
    ports:
      - '3000:80'
    depends_on:
      - db
      - db-test
    links:
      - db
      - db-test
networks:
  default:
