version: '3.1'

services:
  db:
    image: postgres:12.5-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: my_app
      POSTGRES_DB: my_app
    container_name: toolkit_db
    ports:
      - 54321:5432
    restart: 'no'
    volumes:
      - ./data:/var/lib/postgresql/data

  db-test:
    image: postgres:12.5-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: my_app
      POSTGRES_DB: my_app_test
    container_name: toolkit_db_test
    ports:
      - 54322:5432
    restart: 'no'

  app:
    privileged: true
    container_name: cake_test_app
    env_file:
      - .env
    build: .
    volumes:
      - .:/var/www/html
      - ./mount.sh:/mount.sh
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
      - NET_ADMIN
    command: bash -c "chmod 755 /mount.sh && /mount.sh && apachectl -D FOREGROUND"
    ports:
      - 5000:80
    depends_on:
      - db
      - db-test
